### ISSUE TITLE
lambda.null_resource.archive[0] must be replaced

### ISSUE THREAD

**Issue by zakabluk** [terraform-aws-modules/terraform-aws-lambda#179]
I faced again with same issue https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/51
```
terraform 0.14 or 1.x.x
source  = "terraform-aws-modules/notify-slack/aws"
version = "4.17.0"
```
 every new user who launched terraform plan or terraform apply faced with
```
  # module.startrack_use1.module.startrack_notify.module.lambda.null_resource.archive[0] must be replaced
-/+ resource "null_resource" "archive" {
      ~ id       = "6504200727608114944" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "timestamp" = "1626339685388688077" -> "<WARNING: Missing lambda zip artifacts wouldn't be restored>"
            # (1 unchanged element hidden)
        }
    }
```
last test was on macOS
python --version
Python 2.7.16
Terraform v1.0.2
on darwin_amd64

**Comment by antonbabenko** [comment]
Lambda module has been fixed some time ago but you are referring to `terraform-aws-modules/notify-slack/aws` which is still using an older version of the Lambda module.

I am going to close this issue in the repo.

**Comment by sastels** [comment]
`terraform-aws-modules/notify-slack/aws` is now using 2.27.1 and still having this problem.
